Model, MovieDao, MovieService,HibernateUtil classes implemented
semyonich/cinema pull request #1
Opened 2021-01-26 14:26 UTC by semyonich

2021-01-26 15:51 UTC, NikolayFatkullin approved these changes

2021-01-26 16:36 UTC, Sofasmile requested changes

2021-01-26 16:36 UTC, Sofasmile commented on src/main/java/com/cinema/dao/impl/MovieDaoImpl.java
> +            movie.setId(movieId);
https://mate-academy.github.io/jv-program-fulltime/03_hibernate/checklist/hibernate_01.html

2021-01-26 16:36 UTC, Sofasmile commented on src/main/java/com/cinema/dao/impl/MovieDaoImpl.java
> +            throw new RuntimeException("Unable to add " + movie.getTitle() + "to DB", e);
let's create your custom exception

2021-01-26 17:35 UTC, semyonich commented on src/main/java/com/cinema/dao/impl/MovieDaoImpl.java
> +            movie.setId(movieId);
done

2021-01-26 17:35 UTC, semyonich commented on src/main/java/com/cinema/dao/impl/MovieDaoImpl.java
> +            throw new RuntimeException("Unable to add " + movie.getTitle() + "to DB", e);
done

2021-01-27 07:11 UTC, Sofasmile approved these changes

2021-01-27 07:24 UTC, merged